### ISSUE TITLE
deadline_test is with wrong app name

### ISSUE THREAD

**Issue by locnnil** [canonical/rt-tests-snap#7]
The `deadline_test` app name is wrong at the [snapcraft.yaml file](https://github.com/canonical/rt-tests-snap/blob/36184401540f86e59f94f9cfa64adb33c3207239/snap/snapcraft.yaml#L50), which can causes incompatibilities.

**Comment by farshidtz** [comment]
Underscores are not allowed in snap names. I've proposed changing the name to deadline-test in #14, making it consistent with pip-stress (executable pip_stress) and pi-stress (pi_stress).
